# Generated by Django 4.1.3 on 2023-10-31 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la cual fue creado.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue actualizdo por últimavez.', verbose_name='updated at')),
                ('client', models.IntegerField(verbose_name='Client')),
                ('issuance_date', models.DateTimeField(verbose_name='Issuance date')),
                ('billing_date', models.DateTimeField(null=True, verbose_name='Billing date')),
                ('invoice_number', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(choices=[('1', 'INVOICED'), ('2', 'PENDING')], default='2', max_length=1)),
                ('total_purchase', models.IntegerField(default=0, verbose_name='Total purchase')),
                ('total_sale', models.IntegerField(default=0, verbose_name='Total sale')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotation',
                'db_table': 'quotations',
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuoteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la cual fue creado.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue actualizdo por últimavez.', verbose_name='updated at')),
                ('provider', models.IntegerField()),
                ('item', models.IntegerField()),
                ('purchase_price', models.FloatField(verbose_name='Purchase price')),
                ('quantity', models.IntegerField(verbose_name='Current consumption')),
                ('selling_price', models.FloatField(verbose_name='Selling price')),
                ('total_purchase', models.FloatField(verbose_name='Total Purchase')),
                ('total_sale', models.FloatField(verbose_name='Total Sale')),
                ('profit', models.IntegerField(verbose_name='Profit')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.quotation')),
            ],
            options={
                'verbose_name': 'Quote detail',
                'verbose_name_plural': 'Quotes detail',
                'db_table': 'quote_detail',
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
